name: NDK build

on:
  push:
    branches: [ master, so-update ]
  pull_request:
    branches: [ master, so-update ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      name: Checkout
      with:
        submodules: true
        lfs: true
    - name: Build using QPM and NDK
      id: qpm-build
      uses: sc2ad/QuestNDKBuildAction@v0.1.1
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workspace: ${GITHUB_WORKSPACE}
    - name: Upload non-debug artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.qpm-build.outputs.libname }}
        path: ${{ steps.qpm-build.outputs.release-path }}
        if-no-files-found: error
    - name: Upload debug artifact
      uses: actions/upload-artifact@v2
      with:
        name: debug_${{ steps.libname.outputs.NAME }}
        path: ${{ steps.qpm-build.outputs.debug-path }}
        if-no-files-found: error
    # TODO: Add auto-populating releases, auto update versions, auto publish package on release
